/**
 *
 * BlueArchLayout
 *
 *  */

import React from 'react';
import styled from 'styled-components';

import { Mobile, Tablet } from 'components/Utils';

interface Props {}

const BlueArchLayout = (props: Props) => {
  return (
    <BlueBG>
      <Mobile>
        <TextWrapper>
          <p style={{ textAlign: 'right' }}>
            We started forming our team in the early 2000s, guided by our
            passion for research and analytics and a collective data-centric
            mindset.
          </p>
          <p>
            When we looked deeper trying to understand how much value is
            generated by businesses from their data and digital assets, we
            discovered a problem impossible to solve with the existing
            technology solutions not fit for purpose.
          </p>
        </TextWrapper>
        <TextWrapper>
          <p style={{ textAlign: 'right' }}>
            Over the past decade, it has become more and more apparent that data
            is the ultimate artifact of our lives and it is held firm in our
            belief that this digital byproduct is the most valuable impression
            created by all our digital activities.
          </p>
          <p>
            Just to find and catalogue data was an incredible task even before
            confronting the now so evident issue of data sprawl and seeing how
            executives struggled to answer the most basic question – “what data
            do we have
          </p>
        </TextWrapper>
        <MobileShipsWrapper>
          <ShipsImg src="/static/img/Team/ships@2x.png" />
        </MobileShipsWrapper>
      </Mobile>
      <StyledTablet>
        <TabletTextWrapper>
          <p style={{ textAlign: 'right' }}>
            We started forming our team in the early 2000s, guided by our
            passion for research and analytics and a collective data-centric
            mindset.
          </p>
          <p style={{ textAlign: 'right' }}>
            Over the past decade, it has become more and more apparent that data
            is the ultimate artifact of our lives and it is held firm in our
            belief that this digital byproduct is the most valuable impression
            created by all our digital activities.
          </p>
        </TabletTextWrapper>
        <TabletShipsWrapper>
          <VerticalShipsImg src="/static/img/Team/vertical-ships@2x.png" />
        </TabletShipsWrapper>
        <TabletTextWrapper style={{ alignItems: 'flex-start' }}>
          <p>
            When we looked deeper trying to understand how much value is
            generated by businesses from their data and digital assets, we
            discovered a problem impossible to solve with the existing
            technology solutions not fit for purpose.
          </p>
          <p>
            Just to find and catalogue data was an incredible task even before
            confronting the now so evident issue of data sprawl and seeing how
            executives struggled to answer the most basic question – “what data
            do we have
          </p>
        </TabletTextWrapper>
      </StyledTablet>
    </BlueBG>
  );
};

export default BlueArchLayout;

const MobileShipsWrapper = styled.div`
  text-align: center;
`;

const ShipsImg = styled.img`
  width: calc(100% - 60px);
`;

const BlueBG = styled.div`
  background-color: #67bfd6;
  width: 100%;
  min-height: 500px;
  margin-top: 50px;
  p {
    font-family: 'NewPro-Light', sans-serif;
  }
`;

const TextWrapper = styled.div`
  display: flex;
  justify-content: space-around;

  p {
    width: 50%;
    margin-left: 30px;
    margin-right: 30px;
  }
`;

//
// Tablet styles
//
const TabletShipsWrapper = styled.div`
  text-align: center;
  ${({ theme }) => theme.media.max.tablet`
    display: none;
  `}
`;

const StyledTablet = styled(Tablet)`
  display: flex;
  align-items: center;
  ${({ theme }) => theme.media.max.tablet`
    display: none;
  `}
`;

const TabletTextWrapper = styled.div`
  display: flex;
  flex-direction: column;
  align-items: flex-end;

  p {
    width: 90%;
  }
`;

const VerticalShipsImg = styled.img`
  width: 140%;
  transform: translate(5%, 12%);
  ${({ theme }) => theme.media.min.desktop`
    transform: translate(5%, 15%);
  `}
`;
